version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: cinemaplus-postgres
    environment:
      POSTGRES_DB: cinemaplus
      POSTGRES_USER: cinemaplus
      POSTGRES_PASSWORD: cinemaplus
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: